apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: service-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-demo
  template:
    metadata:
      labels:
        app: service-demo
    spec:
      containers:
      - name: service-demo
        image: franklynvidal/servicenet5:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: service-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: http
